"""PostgreSQL integration test for the LangGraph checkpoint path.

Why this file exists
--------------------
``tests/test_indexing_graph.py`` covers checkpointing against SQLite, which is what a developer
runs locally. Production runs the worker on PostgreSQL, and that path is different code:
``IndexingGraphRunner._open_postgres_checkpointer`` uses ``psycopg`` directly and puts the
checkpointer in its own schema. Nothing proved that path worked, because CI had no database.

The properties asserted here are the ones the design promises:

1. **The checkpoint schema is created and populated** — the pipeline actually completes.
2. **Checkpoints never touch the application schema** — the application tables stay in
   ``public``, checkpoint tables live in ``langgraph_checkpoint``, so autogenerate never sees
   them. On SQLite this is proven by a separate file; PostgreSQL shares one database, so the
   schema is the only thing keeping them apart.
3. **Resume works over PostgreSQL** — a worker that dies mid-pipeline does not pay twice for
   the embedding batches that already succeeded. This is the commercial reason for the graph.

Running it
----------
Set ``IT_TEST_POSTGRES_URL`` to a server the current role may create databases on, and the
module runs against a disposable database it creates and drops itself::

    IT_TEST_POSTGRES_URL=postgresql+psycopg://docmind:change-me@127.0.0.1:5432/docmind_it \\
        python -B -m unittest tests.test_indexing_graph_postgres -v

Without that variable every test is skipped, so the default suite stays green on a machine
with no PostgreSQL.
"""
from pathlib import Path
import os
import tempfile
import unittest
from urllib.parse import urlsplit, urlunsplit

from alembic import command
from alembic.config import Config
from alembic.util.exc import AutogenerateDiffsDetected
from fastapi.testclient import TestClient

from admin_app import create_admin_app
from backend import AppSettings, DocumentSourceStore, QueryDatabase
from backend.embeddings import EmbeddingClient, EmbeddingError
from ingestion import DocumentIngestionService
from worker.graph import CHECKPOINT_SCHEMA, langgraph_available
from worker.runner import IngestionWorker


ROOT = Path(__file__).resolve().parents[1]
CONTENT = (
    "# 打印机\n## 驱动安装\nzebra printer driver 需要重新安装驱动。\n"
    "## 纸张设置\n请选择 A4 纸张并重新校准。\n"
    "## 网络打印\n请检查打印服务器地址与端口。\n"
    "## 常见故障\n卡纸时请先断电再取出纸张。\n"
)

POSTGRES_URL = os.environ.get("IT_TEST_POSTGRES_URL", "").strip()


def server_url(database_url: str, database: str) -> str:
    """Same server, different database. Used for CREATE/DROP DATABASE."""
    parts = urlsplit(database_url)
    return urlunsplit((parts.scheme, parts.netloc, f"/{database}", "", ""))


def connect(database_url: str, *, autocommit: bool = True):
    """psycopg connection for the maintenance statements psycopg2/SQLAlchemy cannot run."""
    from psycopg import connect as psycopg_connect

    dsn = database_url.replace("postgresql+psycopg://", "postgresql://", 1)
    return psycopg_connect(dsn, autocommit=autocommit)


class CountingEmbeddingClient(EmbeddingClient):
    """Hash embeddings with a call counter; no network is involved."""

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.calls = 0

    def embed(self, texts, *, request_id: str = ""):
        self.calls += 1
        return super().embed(texts, request_id=request_id)


class FlakyEmbeddingClient(CountingEmbeddingClient):
    """Fails deterministically once a number of batches have succeeded."""

    def __init__(self, *, succeed_first: int, **kwargs):
        super().__init__(**kwargs)
        self.succeed_first = succeed_first

    def embed(self, texts, *, request_id: str = ""):
        if self.calls >= self.succeed_first:
            self.calls += 1
            raise EmbeddingError("embedding_unavailable")
        return super().embed(texts, request_id=request_id)


@unittest.skipUnless(POSTGRES_URL, "IT_TEST_POSTGRES_URL is not set")
@unittest.skipUnless(langgraph_available(), "worker extras are not installed")
class PostgresCheckpointTests(unittest.TestCase):
    """A disposable database per test.

    Sharing one database across tests couples them through content-keyed behaviour: importing
    the same document twice is a no-op by design (``uq_document_versions_hash``), so a second
    test would get a duplicate response instead of a queued one. One database per test removes
    every shared-state assumption, at the cost of one extra migration run.
    """

    def setUp(self):
        if not POSTGRES_URL.startswith("postgresql"):
            self.skipTest("IT_TEST_POSTGRES_URL must be a postgresql:// URL")
        self.database_name = f"docmind_it_test_{os.getpid()}_{os.urandom(3).hex()}"
        self.database_url = server_url(POSTGRES_URL, self.database_name)
        with connect(server_url(POSTGRES_URL, "postgres")) as connection:
            with connection.cursor() as cursor:
                cursor.execute(f'CREATE DATABASE "{self.database_name}"')
        self.alembic_config = Config(str(ROOT / "alembic.ini"))
        self.alembic_config.attributes["database_url"] = self.database_url
        command.upgrade(self.alembic_config, "head")

    def tearDown(self):
        if not self.database_name:
            return
        with connect(server_url(POSTGRES_URL, "postgres")) as connection:
            with connection.cursor() as cursor:
                try:
                    # PostgreSQL 13+ can evict leftover sessions instead of refusing to drop.
                    cursor.execute(f'DROP DATABASE IF EXISTS "{self.database_name}" WITH (FORCE)')
                except Exception:  # noqa: BLE001 - fall back on older servers
                    cursor.execute(f'DROP DATABASE IF EXISTS "{self.database_name}"')
        self.database_name = ""

    # -- helpers ---------------------------------------------------------------
    def make_settings(self, root: str, *, engine: str = "langgraph") -> AppSettings:
        project = Path(root)
        knowledge = project / "knowledge.md"
        knowledge.write_text("# IT\n", encoding="utf-8")
        web = project / "web" / "index.html"
        web.parent.mkdir(parents=True, exist_ok=True)
        web.write_text("<!doctype html>", encoding="utf-8")
        return AppSettings(
            project_root=project,
            environment="test",
            database_url=self.database_url,
            knowledge_path=knowledge,
            web_index_path=web,
            artifact_output_path=project / "artifacts",
            auth_mode="trusted_headers",
            auth_subject_salt="unit-test-subject-salt",
            log_level="CRITICAL",
            governance_mode="direct",
            ingestion_worker_enabled=True,
            ingestion_engine=engine,
        )

    def worker_with_client(self, settings: AppSettings, client: EmbeddingClient):
        database = QueryDatabase(settings.database_url)
        ingestion = DocumentIngestionService(
            database, client,
            max_bytes=settings.document_max_bytes,
            chunk_max_chars=settings.chunk_max_chars,
            chunk_overlap_chars=settings.chunk_overlap_chars,
            max_characters=settings.document_max_characters,
            max_pages=settings.document_max_pages,
            require_review=settings.governance_mode == "review",
        )
        worker = IngestionWorker(
            settings=settings, database=database, ingestion=ingestion,
            sources=DocumentSourceStore(settings.project_root / "data" / "sources"),
            worker_id="pg-graph-test", engine="langgraph",
        )
        return worker, database

    def import_document(self, client: TestClient) -> dict:
        response = client.post(
            "/api/admin/documents/import",
            headers={"X-Auth-Subject": "editor-1", "X-Auth-Roles": "knowledge_editor"},
            files={"file": ("printer.md", CONTENT.encode("utf-8"), "text/markdown")},
            # Keyed by test name: re-importing identical content is a deliberate no-op, so a
            # shared key would turn a second test's import into a duplicate response.
            data={"source_key": f"manual/{self._testMethodName}", "access_scope": "public",
                  "classification": "internal"},
        )
        self.assertEqual(response.status_code, 202, response.text)
        return response.json()

    def table_names(self, schema: str) -> list:
        with connect(self.database_url) as connection:
            with connection.cursor() as cursor:
                cursor.execute(
                    "SELECT table_name FROM information_schema.tables WHERE table_schema = %s",
                    (schema,),
                )
                return sorted(row[0] for row in cursor.fetchall())

    def assert_checkpoints_are_schema_isolated(self, alembic_config: Config) -> None:
        """A-2's real invariant: checkpoints must not reach the application schema."""
        application_tables = self.table_names("public")
        self.assertTrue(application_tables, "the application schema should hold the app tables")
        self.assertFalse(
            [name for name in application_tables if "checkpoint" in name.lower()],
            f"checkpoint tables leaked into public: {application_tables}",
        )

        checkpoint_tables = self.table_names(CHECKPOINT_SCHEMA)
        self.assertTrue(
            checkpoint_tables,
            f"the {CHECKPOINT_SCHEMA} schema should hold the checkpoint tables",
        )
        self.assertTrue(any("checkpoint" in name.lower() for name in checkpoint_tables))

        # Autogenerate is the tool that would notice a stray table. Report unrelated drift
        # rather than failing on it: only checkpoint leakage is this test's business.
        try:
            command.check(alembic_config)
        except AutogenerateDiffsDetected as exc:
            self.assertNotIn(
                "checkpoint", str(exc).lower(),
                "alembic discovered checkpoint tables in the application schema",
            )

    # -- tests -----------------------------------------------------------------
    def test_checkpointed_indexing_runs_on_postgres_and_stays_out_of_the_app_schema(self):
        with tempfile.TemporaryDirectory() as root:
            alembic_config = self.alembic_config
            settings = self.make_settings(root)
            application = create_admin_app(settings)
            database = QueryDatabase(settings.database_url)
            try:
                with TestClient(application) as client:
                    imported = self.import_document(client)

                worker, worker_database = self.worker_with_client(
                    settings,
                    CountingEmbeddingClient(mode="hash", provider="builtin", model="hash-1024",
                                            base_url="", api_key="", dimension=1024,
                                            batch_size=1),
                )
                try:
                    self.assertEqual(worker.drain(), 1)
                finally:
                    worker.close()
                    worker_database.dispose()

                # Filter by this test's own document: both tests share one database, so the
                # assertions must not depend on which one unittest happens to run first.
                rows = [row for row in database.list_documents()
                        if row["document_id"] == imported["document_id"]]
                self.assertEqual([row["status"] for row in rows], ["indexed"])
                self.assertGreater(database.count_document_chunks(imported["version_id"]), 0)
                self.assertTrue(
                    database.lexical_search("zebra", subject_id="v1", roles=("viewer",)),
                )
                self.assert_checkpoints_are_schema_isolated(alembic_config)
            finally:
                database.dispose()

    def test_resume_over_postgres_does_not_re_embed_finished_batches(self):
        with tempfile.TemporaryDirectory() as root:
            alembic_config = self.alembic_config
            settings = self.make_settings(root)
            application = create_admin_app(settings)
            database = QueryDatabase(settings.database_url)
            try:
                with TestClient(application) as client:
                    imported = self.import_document(client)
                    version_id = imported["version_id"]
                    document_id = imported["document_id"]
                    source = settings.project_root / "data" / "sources" / str(document_id)
                    source_file = next(source.glob("v1-*"))
                total_chunks = self.expected_chunk_count(settings, source_file)

                # First attempt: two batches succeed, then the provider goes away.
                flaky = FlakyEmbeddingClient(
                    succeed_first=2, mode="hash", provider="builtin", model="hash-1024",
                    base_url="", api_key="", dimension=1024, batch_size=1,
                )
                first_worker, first_database = self.worker_with_client(settings, flaky)
                try:
                    outcome = first_worker.run_once()
                finally:
                    first_worker.close()
                    first_database.dispose()
                self.assertEqual(outcome["status"], "queued")
                self.assertTrue(outcome["retryable"])
                self.assertEqual(database.count_document_chunks(version_id), 2)
                self.assertTrue(list(source.glob("*.chunks.json")))

                # The checkpoint really is in PostgreSQL, not in a local file.
                self.assertTrue(self.table_names(CHECKPOINT_SCHEMA))

                # Second attempt resumes: only the remaining batches are embedded again.
                healthy = CountingEmbeddingClient(
                    mode="hash", provider="builtin", model="hash-1024",
                    base_url="", api_key="", dimension=1024, batch_size=1,
                )
                second_worker, second_database = self.worker_with_client(settings, healthy)
                try:
                    self.assertEqual(second_worker.run_once()["status"], "succeeded")
                finally:
                    second_worker.close()
                    second_database.dispose()

                self.assertEqual(healthy.calls, total_chunks - 2)
                self.assertEqual(database.count_document_chunks(version_id), total_chunks)
                self.assert_checkpoints_are_schema_isolated(alembic_config)
            finally:
                database.dispose()

    def expected_chunk_count(self, settings: AppSettings, path: Path) -> int:
        from ingestion.chunker import chunk_document
        from ingestion.parsers import parse_document

        parsed = parse_document(
            path, title="", max_bytes=settings.document_max_bytes,
            max_characters=settings.document_max_characters, max_pages=settings.document_max_pages,
        )
        return len(chunk_document(
            parsed, max_chars=settings.chunk_max_chars,
            overlap_chars=settings.chunk_overlap_chars,
        ))


if __name__ == "__main__":
    unittest.main()
